name: Build and Push Docker Image

on:
  pull_request:
    branches:
      - main

env:
  CLUSTER_NAME: cluster
  INFRA_SSH_HOST: ssh.tiggomark.com.br
  INFRA_SSH_PORT: 22
  INFRA_SSH_USERNAME: root
  DOCKERHUB_USERNAME: tiggomark

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: tiggomark/evolution-api:latest

      - name: Update Cluster
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ env.INFRA_SSH_HOST }}
          username: ${{ env.INFRA_SSH_USERNAME }}
          password: ${{ secrets.INFRA_SSH_PASSWORD }}
          port: ${{ env.INFRA_SSH_PORT }}
          script: |
            docker login -u ${{ env.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker pull tiggomark/evolution-api:latest
            docker service update --image tiggomark/evolution-api:latest --detach=false --force cluster_whatsapp_api
            docker service update --image nginx --detach=false --force cluster_nginx